# See https://www.chirpstack.io/network-server/install/config/ for a full
# configuration example and documentation.
#
# This file is for the EU868 band. See the examples/ folder for more
# configuration examples.
[general]
# Log level
#
# debug=5, info=4, warning=3, error=2, fatal=1, panic=0
log_level=4

[postgresql]
dsn="postgres://chirpstack_ns:chirpstack_ns@postgresql/chirpstack_ns?sslmode=disable"

[redis]
url="redis://redis:6379"

[network_server]
net_id="000000"

[network_server.band]
name="AS_923"

[network_server.network_settings]
enabled_uplink_channels=[]
  [[network_server.network_settings.extra_channels]]
  frequency=923600000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=923800000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=924000000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=924200000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=924400000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=924600000
  min_dr=0
  max_dr=5

[network_server.gateway.backend.mqtt]
server="tcp://mosquitto:1883"

[join_server.default]
server="http://chirpstack-application-server:8003"

[geolocation_server]
server="chirpstack-geolocation-server:8005"
